// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL60RHSrTx4b10oWEQqxxt46zlDE7EXWs',
    appId: '1:605459084539:web:a1430b438ae0b009d76c5e',
    messagingSenderId: '605459084539',
    projectId: 'ephealth-desafio',
    authDomain: 'ephealth-desafio.firebaseapp.com',
    storageBucket: 'ephealth-desafio.appspot.com',
    measurementId: 'G-M8MJTGDFDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdV985CDXsF-y6w17tWUeitjLHdKzUWuU',
    appId: '1:605459084539:android:4b13d901c214f2add76c5e',
    messagingSenderId: '605459084539',
    projectId: 'ephealth-desafio',
    storageBucket: 'ephealth-desafio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1xh31kUHWguvgcQF8TIurLkB9JzBWJvI',
    appId: '1:605459084539:ios:3202fb1640211043d76c5e',
    messagingSenderId: '605459084539',
    projectId: 'ephealth-desafio',
    storageBucket: 'ephealth-desafio.appspot.com',
    iosClientId: '605459084539-rlr764bkiibi5o0qqvi4ftg2aofkq5js.apps.googleusercontent.com',
    iosBundleId: 'com.example.ephealthDesafioFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1xh31kUHWguvgcQF8TIurLkB9JzBWJvI',
    appId: '1:605459084539:ios:3202fb1640211043d76c5e',
    messagingSenderId: '605459084539',
    projectId: 'ephealth-desafio',
    storageBucket: 'ephealth-desafio.appspot.com',
    iosClientId: '605459084539-rlr764bkiibi5o0qqvi4ftg2aofkq5js.apps.googleusercontent.com',
    iosBundleId: 'com.example.ephealthDesafioFlutter',
  );
}
